### PR TITLE
Promise chainings and Powerstrip

### PR DESCRIPTION
**Pull request by fantomnotabene**
[miIO](https://github.com/aholstenson/miio) methods are returning Promises, witch [can be](https://developer.athom.com/docs/apps/Device.html) nicely handled by capability listeners.
P.S. The ```UnhandledPromiseRejectionWarning: Error: invalid_capability``` in stderr is not my bad.

### CODE REVIEW

**Comment by fantomnotabene** [comment]
#16 partially implemented

**Comment by jghaanstra** [comment]
Nice going, should I merge already or are you working on more improvements?

**Comment by jghaanstra** [comment]
Thanx, merged.

**Comment by fantomnotabene** [comment]
If there will be another thing I can do, I’ll send another PR. Sorry for my English, hope that the message is clearly understood :)

**Pull request merged**
